name: Build elf-tools (Windows)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: MINGW64
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-meson
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-pkgconf
            git
            flex
            bison

      # 关键：在克隆 elf-tools 之前设置 Git 全局重写（SSH -> HTTPS）
      - name: Force submodules to use HTTPS
        shell: msys2 {0}
        run: |
          git config --global url."https://github.com/".insteadOf git@github.com:
          git config --global url."https://github.com/".insteadOf ssh://git@github.com/

      - name: Clone nunuhara/elf-tools (with submodules)
        shell: msys2 {0}
        run: |
          set -e
          git clone --recurse-submodules https://github.com/nunuhara/elf-tools.git
          cd elf-tools
          # 保险起见，显式同步并再次确保 .gitmodules 改为 HTTPS
          sed -i 's#git@github.com:#https://github.com/#g' .gitmodules || true
          git submodule sync --recursive
          git submodule update --init --recursive

          meson setup build --buildtype=release
          ninja -C build

      - name: Pack artifact (exe + README + SHA256)
        shell: bash
        run: |
          set -e
          mkdir -p out
          cp elf-tools/build/elf.exe out/
          cp elf-tools/README.md out/
          cd out
          COMMIT=$(git -C ../elf-tools rev-parse --short HEAD)
          mv elf.exe "elf_${COMMIT}.exe"
          certutil -hashfile "elf_${COMMIT}.exe" SHA256 > SHA256.txt 2>&1 || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: elf-tools-windows
          path: out
