name: Build elf-tools (Windows)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: MINGW64
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-meson
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-pkgconf
            mingw-w64-x86_64-flex
            mingw-w64-x86_64-bison
            git

      - name: Clone nunuhara/elf-tools
        shell: msys2 {0}
        run: |
          git clone https://github.com/nunuhara/elf-tools.git
          cd elf-tools
          meson setup build --buildtype=release
          ninja -C build

      - name: Pack artifact
        shell: bash
        run: |
          mkdir -p out
          cp elf-tools/build/elf.exe out/
          cp elf-tools/README.md out/
          cd out
          sha256sum elf.exe > SHA256.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: elf-tools-windows
          path: out
